server: 
  port: 3344 

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name:  microservicecloud-config-center-bus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuxian89/microservicecloud-config.git #GitHub上面的git仓库名字
          search-paths: springcloud-learn

